### ISSUE TITLE
Easee equalizer import energy

### ISSUE THREAD

**Issue by onelius** [nordicopen/easee_hass#243] opened 2022-10-31 19:48 UTC
### The problem

The Easee equalizer import energy shows the value with decimal in the wrong place.

Example:
shows 521961,0 kwh, but the correct value is 52196,1 kwh

### Version of Easee integration having the issue?

v0.9.45

### Version of Home Assistant Core having the issue?

2022.9.7

**Comment by olalid** [comment] 2022-10-31 21:43
Since this is most likely a bug in the equalizer and not in the HA component (you probably see the same incorrect value in the easee app, right?) you should contact Easee about this.

**Comment by onelius** [comment] 2022-11-01 05:48
Found it on the Easee app and that is tight, it's the wrong value there too. 

I have sent a bug report to Easee now.

**Comment by runevad** [comment] 2022-11-20 14:01
Any update on this? My dad's meter seems to be very buggy and reporting all over the place...

**Comment by olalid** [comment] 2022-11-20 15:14
Please report your problem to Easee, we are not able to do anything about this at our end.

**Comment by onelius** [comment] 2022-11-20 15:24
Contact Easee support, they made a firmvare update for me and now everything works fine :)

**Comment by olalid** [comment] 2023-03-31 09:43
Are you saying that is behaves randomly such that the decimal point moves back and forth?
Does the Easee app show the same values as the HA integration?

The only conversion we do is to change between kWh and Wh depending on the settings you selected in the integration. A division or multiplication by 10 should not be possible.

If you enable debug logging, you can see what the values that are transferred from the easee cloud are.
Add this to your configuration.yaml:
```
logger:
  default: info
  logs:
    pyeasee: debug
    custom_components.easee: debug
```
Then you should see the corresponding data in the log file by searching for lines that look like this:
```
Callback xxxxx 45 state_cumulativeActivePowerImport 73262.7265625
Callback xxxxx 46 state_cumulativeActivePowerExport 11993.2900390625
```
This is the raw data that is sent by the cloud. If it is wrong already here, there is not much we can do...

**Comment by larsosca** [comment] 2023-04-01 07:17
It seems to be randomly, however report on the hour are almost every time correct.
Thank you for the logger parameters, I have been looking for a way to log readings, and will implement this a.s.a.p.

**Comment by larsosca** [comment] 2023-04-01 10:47
Thank you for the tip on how to debug log the integration!

As @onelius earlier wrote I could today caught Easee cloud having the same wrong decimal positions as I experience it in the integration.
It was actually for all cumulative values and not only import and export as I first thought.
Easee support claims that this can be caused by drop out of connection between the Equalizer and easee.cloud, but I have a hard time believing that a real time reading could move the value by 10 times up and down depending on a connection dropout.
I have reported it again, awaiting response coming week.

**Comment by larsosca** [comment] 2023-04-06 17:26
Update: If some one else ends up here for help with the same issue.
Easee support has finally recognized that there is a problem with the Equalizer integration to "Some Swedish Aidon meters".
They wrote: _"Some Swedish Aidon meters output the energy value at 10x of what they should. The Equalizer code has some compensation for it. But it appears to not be perfect. I have escalated the issue, and we will look into it."_
I am waiting for their correction.

**Comment by larsosca** [comment] 2023-06-16 11:41
Update: Two month later Easee still hasn't been able to correct the erroneous meter reading by Easee Equalizer from Swedish Aidon meters.

**Comment by larsosca** [comment] 2023-06-16 11:57
@fondberg
First: Is there a way to correct historic data for the integration and that way being able to look back on correct data?
I have DB access and have been able to identified wrong stored reported data but it will not affect my energy-usage-graph.
Is that stored in a different table?

Secondly,  is it possible to change the code locally in my HA, to divide the measurement by 10 if the new reported value is greater that 10 times the previous reported value?

**Closed** 2024-02-06 10:43 UTC
Labels: bug, support
